[project]
name = "ds1rand"
dynamic = ["version"]
description = "Parameter randomizer for Dark Souls: Remastered"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "PySide6>=6.6",
    "soulstruct==2.6.0",
]

[dependency-groups]
build = [
    "pyinstaller>=6.11",
]
dev = ["pytest"]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
version = {attr = "ds1rand.__version__"}

[project.scripts]
ds1rand-cli = "ds1rand.cli:main"

[project.gui-scripts]
ds1rand = "ds1rand.ui.app:main"

[tool.setuptools.packages.find]
include = ["ds1rand*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
